version: '3.2'

services:
  pqai_encoder_api:
    container_name: prod_pqai_reranker_api
    build: .
    command: bash -c "pip install --no-cache-dir --upgrade -r /code/requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"
    restart: always
    ports: 
      - 8004:80
    volumes:
      - type: bind
        source: ./assets
        target: /code/assets
    environment:
      - PORT=${PORT}
